# Zmqpp

language: cpp

os:
  - linux
  - osx

compiler:
  - g++

env:
  - ZMQ_REPO=libzmq    BUILD_TYPE=default WITH_LIBSODIUM=1


before_install:
  # Linux pre-install
  - if [ "$CXX" == "g++" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:smspillaz/cmake-2.8.12; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  # OS X pre-install
  - if [ "TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

install:
  # Install dependencies for linux
  # g++4.8.1
  - if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -q -y g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  # cmake (2.8.12 or higher)
  - if [ "$TRAVIS_OS_NAME" == "linux"]; then sudo apt-get install -q -y cmake-data cmake; fi
  # Requirements
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -q -y libboost-all-dev; fi

  # Install dependencies for OS X
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gnu-sed --with-default-names; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install libtool; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CC=gcc-4.8; export CXX=g++-4.8; fi

script:
  - ./travis.sh
